// <auto-generated />
namespace ShopperApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Scan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Scan));
        
        string IMigrationMetadata.Id
        {
            get { return "202108041003524_Scan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
